name: Branch Name Validation

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - name: Validate branch name pattern
        run: |
          if [[ ! "${BRANCH_NAME}" =~ ^ws1feat\/[a-z0-9\-]+$ ]]; then
            echo "❌ Branch name '${BRANCH_NAME}' does not match pattern 'ws1feat/name-name'"
            exit 1
          else
            echo "✅ Branch name valid: ${BRANCH_NAME}"
          fi
