name: Branch Name Validation

on:
  pull_request:

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - name: Skip main and development
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'development' }}
        run: |
          echo "✅ Branch is main or development, skipping validation."
          exit 0

      - name: Validate branch name pattern
        if: ${{ env.BRANCH_NAME != 'main' && env.BRANCH_NAME != 'development' }}
        run: |
          # Patrón permitido:
          # ws1feat/<nombre>
          # bugfix/<nombre>
          # hotfix/<nombre>
          # release/<nombre>
          PATTERN="^(ws1feat|bugfix|hotfix|release)\/[a-z0-9\-_]+$"

          if [[ ! "${BRANCH_NAME}" =~ $PATTERN ]]; then
            echo "❌ Branch name '${BRANCH_NAME}' does not match pattern '${PATTERN}'"
            exit 1
          else
            echo "✅ Branch name valid: ${BRANCH_NAME}"
