name: Branch Name Validation

on:
  pull_request:

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - name: Skip main and development
        if: ${{ env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'development' }}
        run: |
          echo "✅ Branch is main or development, skipping validation."
          exit 0

      - name: Validate branch name pattern
        if: ${{ env.BRANCH_NAME != 'main' && env.BRANCH_NAME != 'development' }}
        shell: bash
        run: |
          PATTERN="^(ws1feat|bugfix|hotfix|release)/[a-z0-9_-]+$"

          if echo "${BRANCH_NAME}" | grep -Eq "$PATTERN"; then
            echo "✅ Branch name valid: ${BRANCH_NAME}"
          else
            echo "❌ Branch name '${BRANCH_NAME}' does not match pattern '${PATTERN}'"
            exit 1
          fi


